<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.1</Version>
    <PackageProjectUrl>https://github.com/xivrus/XIVRusUpdater</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CheapLoc" Version="1.1.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Penumbra.Api" Version="5.19.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>
</Project>
