using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace XIVRus.Generators;

[Generator]
public sealed class TranslationComponentGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "XIVRusUpdater.Core.Components.TranslationComponentAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var components = context.SyntaxProvider
            .ForAttributeWithMetadataName(AttributeMetadataName, static (node, _) => node is ClassDeclarationSyntax, static (ctx, _) => Extract(ctx))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!)
            .Collect();

        context.RegisterSourceOutput(components, static (spc, list) => Generate(spc, list));
    }

    private static ComponentModel? Extract(GeneratorAttributeSyntaxContext ctx)
    {
        var args = ctx.Attributes[0].ConstructorArguments;
        if (args.Length != 3) return null;

        var id = args[0].Value as string ?? "";
        var displayName = args[1].Value as string ?? "";
        var description = args[2].Value as string ?? "";

        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;

        var sheetsMember = typeSymbol.GetMembers("Sheets").FirstOrDefault(m => m is IFieldSymbol or IPropertySymbol);
        if (sheetsMember is null) return new ComponentModel(id, displayName, description, Array.Empty<(string, int[])>());

        var syntaxRef = sheetsMember.DeclaringSyntaxReferences.FirstOrDefault();
        if (syntaxRef is null) return new ComponentModel(id, displayName, description, Array.Empty<(string, int[])>());

        var node = syntaxRef.GetSyntax();

        ExpressionSyntax? valueExpr = node switch
        {
            VariableDeclaratorSyntax vds => vds.Initializer?.Value,
            PropertyDeclarationSyntax pds => pds.Initializer?.Value,
            _ => null
        };

        if (valueExpr is null) return new ComponentModel(id, displayName, description, Array.Empty<(string, int[])>());

        var tree = valueExpr.SyntaxTree;
        var model = tree == ctx.SemanticModel.SyntaxTree ? ctx.SemanticModel : ctx.SemanticModel.Compilation.GetSemanticModel(tree);

        var sheets = ExtractSheets(valueExpr, model);
        return new ComponentModel(id, displayName, description, sheets.ToArray());
    }

    private static List<(string Name, int[] Rows)> ExtractSheets(ExpressionSyntax expr, SemanticModel model)
    {
        var result = new List<(string, int[])>();

        InitializerExpressionSyntax? dictInitializer = expr switch
        {
            ObjectCreationExpressionSyntax oce => oce.Initializer,
            ImplicitObjectCreationExpressionSyntax ioce => ioce.Initializer,
            _ => null
        };

        if (dictInitializer is not null)
        {
            foreach (var element in dictInitializer.Expressions)
            {
                if (element is AssignmentExpressionSyntax { Left: ImplicitElementAccessSyntax iea } assign && iea.ArgumentList.Arguments.Count == 1)
                {
                    var key = model.GetConstantValue(iea.ArgumentList.Arguments[0].Expression).Value as string;
                    if (key is not null) result.Add((key, ExtractIntArray(assign.Right, model)));
                }
            }
            return result;
        }

        foreach (var name in ExtractStringArray(expr, model)) result.Add((name, Array.Empty<int>()));

        return result;
    }

    private static IEnumerable<ExpressionSyntax> UnwrapArrayElements(ExpressionSyntax expr) => expr switch
    {
        CollectionExpressionSyntax ce => ce.Elements.OfType<ExpressionElementSyntax>().Select(e => e.Expression),
        ArrayCreationExpressionSyntax { Initializer: { } init } => init.Expressions,
        ImplicitArrayCreationExpressionSyntax iace => iace.Initializer.Expressions,
        InitializerExpressionSyntax ies => ies.Expressions,
        _ => Enumerable.Empty<ExpressionSyntax>()
    };

    private static string[] ExtractStringArray(ExpressionSyntax expr, SemanticModel model) => UnwrapArrayElements(expr).Select(e => model.GetConstantValue(e).Value as string).Where(s => s is not null).Select(s => s!).ToArray();

    private static int[] ExtractIntArray(ExpressionSyntax expr, SemanticModel model) => UnwrapArrayElements(expr).Select(e => model.GetConstantValue(e)).Where(v => v.HasValue && v.Value is int).Select(v => (int)v.Value!).ToArray();

    private static void Generate(SourceProductionContext context, ImmutableArray<ComponentModel> components)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace XIVRusUpdater.Core.Components;");
        sb.AppendLine();
        sb.AppendLine("public static partial class TranslationComponents");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<TranslationComponent> All { get; } = new TranslationComponent[]");
        sb.AppendLine("    {");

        foreach (var c in components.OrderBy(c => c.Id, StringComparer.Ordinal))
        {
            sb.AppendLine("        new(");
            sb.AppendLine($"            {Literal(c.Id)},");
            sb.AppendLine($"            {Literal(c.DisplayName)},");
            sb.AppendLine($"            {Literal(c.Description)},");
            sb.AppendLine("            new Dictionary<string, uint[]>");
            sb.AppendLine("            {");
            foreach (var (name, rows) in c.Sheets)
            {
                var rowsLiteral = rows.Length == 0 ? "Array.Empty<uint>()" : $"new[] {{ {string.Join(", ", rows)} }}";
                sb.AppendLine($"                [{Literal(name)}] = {rowsLiteral},");
            }
            sb.AppendLine("            }),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("TranslationComponents.generated.cs", sb.ToString());
    }

    private static string Literal(string value) => SyntaxFactory.Literal(value).ToString();

    private sealed class ComponentModel : IEquatable<ComponentModel>
    {
        public string Id { get; }
        public string DisplayName { get; }
        public string Description { get; }
        public (string Name, int[] Rows)[] Sheets { get; }

        public ComponentModel(string id, string displayName, string description, (string, int[])[] sheets)
        {
            Id = id;
            DisplayName = displayName;
            Description = description;
            Sheets = sheets;
        }

        public bool Equals(ComponentModel? other) => other is not null && Id == other.Id && DisplayName == other.DisplayName && Description == other.Description && Sheets.Select(s => s.Name).SequenceEqual(other.Sheets.Select(s => s.Name)) && Sheets.Zip(other.Sheets, (a, b) => a.Rows.SequenceEqual(b.Rows)).All(x => x);

        public override bool Equals(object? obj) => Equals(obj as ComponentModel);
        public override int GetHashCode() => Id.GetHashCode();
    }
}
