using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace XIVRus.Generators;

[Generator]
public sealed class TranslationEnginesGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "XIVRusUpdater.Core.Components.TranslationEngineDefinition";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var engines = context.SyntaxProvider
            .ForAttributeWithMetadataName(AttributeMetadataName, static (node, _) => node is ClassDeclarationSyntax, static (ctx, _) => Extract(ctx))
            .Where(static e => e is not null)
            .Select(static (e, _) => e!)
            .Collect();

        context.RegisterSourceOutput(engines, static (spc, list) => Generate(spc, list));
    }

    private static EngineModel? Extract(GeneratorAttributeSyntaxContext ctx)
    {
        var args = ctx.Attributes[0].ConstructorArguments;
        if (args.Length != 5) return null;

        var id = args[0].Value as string ?? "";
        var modName = args[1].Value as string ?? "";
        var displayName = args[2].Value as string ?? "";
        var apiUrl = args[3].Value as string ?? "";
        var formatLiteral = args[4].ToCSharpString();

        return new EngineModel(id, modName, displayName, apiUrl, formatLiteral);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<EngineModel> engines)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine("namespace XIVRusUpdater.Core.Components;");
        sb.AppendLine();
        sb.AppendLine("public static partial class TranslationEngines");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<TranslationEngineDefinition> All { get; } = new TranslationEngineDefinition[]");
        sb.AppendLine("    {");

        foreach (var e in engines.OrderBy(e => e.Id, StringComparer.Ordinal))
        {
            sb.AppendLine($"        new({Literal(e.Id)}, {Literal(e.ModName)}, {Literal(e.DisplayName)}, {Literal(e.ApiUrl)}, {e.FormatLiteral}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    private static IReadOnlyDictionary<string, TranslationEngineDefinition> ById { get; } = All.ToDictionary(x => x.Id);");
        sb.AppendLine();
        sb.AppendLine("    public static TranslationEngineDefinition? Get(string id) => ById.GetValueOrDefault(id);");
        sb.AppendLine("}");

        context.AddSource("TranslationEngines.generated.cs", sb.ToString());
    }

    private static string Literal(string value) => SyntaxFactory.Literal(value).ToString();

    private sealed class EngineModel : IEquatable<EngineModel>
    {
        public string Id { get; }
        public string ModName { get; }
        public string DisplayName { get; }
        public string ApiUrl { get; }
        public string FormatLiteral { get; }

        public EngineModel(string id, string modName, string displayName, string apiUrl, string formatLiteral)
        {
            Id = id;
            ModName = modName;
            DisplayName = displayName;
            ApiUrl = apiUrl;
            FormatLiteral = formatLiteral;
        }

        public bool Equals(EngineModel? other) => 
            other is not null && 
            Id == other.Id && 
            ModName == other.ModName && 
            DisplayName == other.DisplayName && 
            ApiUrl == other.ApiUrl &&
            FormatLiteral == other.FormatLiteral;

        public override bool Equals(object? obj) => Equals(obj as EngineModel);
        public override int GetHashCode() => Id.GetHashCode();
    }
}
